# For Travis CI Configuration
sudo: required

language: java

services:
  - docker

addons:
  sonarcloud:
    organization: logicalsapien
    token: $SONAR_TOKEN

before_install:
  - chmod +x gradlew

script:
  - "./gradlew checkstyleMain checkstyleTest pmdMain pmdTest spotbugsMain spotbugsTest"
  - "./gradlew clean build jacocoTestReport"
  - "./gradlew sonarqube"

after_success:
  - docker --version
