# For Travis CI Configuration
language: java

before_install:
  - chmod +x gradlew

script:
  - "./gradlew clean build jacocoTestReport"
  - "bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r build/reports/jacoco/test/jacocoTestReport.xml"
