# For Travis CI Configuration
sudo: required

language: java

services:
  - docker

addons:
  sonarcloud:
    organization: logicalsapien
    token: $SONAR_TOKEN

before_install:
  - chmod +x gradlew

script:
  - "./gradlew checkstyleMain checkstyleTest pmdMain pmdTest spotbugsMain spotbugsTest"
  - "./gradlew clean build jacocoTestReport"
  - "./gradlew sonarqube"

after_success:
  - docker --version
  - docker build -t rema-api .
  - docker tag rema-api:latest logicalsapien/rema-api:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push logicalsapien/rema-api:latest

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: rema-api
  on: dev
